
# html lang
language: en

# main menu navigation
menu:
  Home: /
  About: /about
  Contact: /contact
  Archives: /archives

# author profile
profile:
  description: C.F. Gorrie is a linguist and software developer in Hamilton, ON.
  image: /img/profile-250x250.jpg
  social:
    twitter: cfgorrie

# Miscelaneous
favicon: /favicon.ico

# stylesheets loaded in the <head>
stylesheets:
- https://yui-s.yahooapis.com/pure/0.6.0/pure-min.css
- https://yui-s.yahooapis.com/pure/0.6.0/grids-responsive-min.css
- https://fonts.googleapis.com/css?family=Reem+Kufi|Crimson+Text:400,400i,700,700i
- https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css
- /css/tradition.css

# scripts loaded in the end of the body
scripts:
- /js/tradition.js
