# html lang
language: en

# main menu navigation
menu:
  Home: /
  About: /about
  Archives: /archives
  Talks: /talks

# author profile
profile:
  description:
  image:
  social:
    twitter: 

# Miscelaneous
favicon: /favicon.ico

# stylesheets loaded in the <head>
stylesheets:
- https://yui-s.yahooapis.com/pure/0.6.0/pure-min.css
- https://yui-s.yahooapis.com/pure/0.6.0/grids-responsive-min.css
- https://fonts.googleapis.com/css?family=Reem+Kufi|Crimson+Text:400,400i,700,700i|Inconsolata
- https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css
- /css/tradition.css

# scripts loaded in the end of the body
scripts:
- /js/tradition.js

# disqus
disqus_shortname:

# google analytics
google_analytics:
