<meta property="og:url" content="{{ url }}">
<meta property="og:type" content="website">
<meta property="og:title" content="{{ page.title }}">
{# <meta property="og:image" content="https://example.com/image.jpg"> #}
<meta property="og:description" content="{{ page.excerpt }}">
<meta property="og:site_name" content="{{ config.title }}">
<meta property="og:locale" content="en_US">
<meta property="article:author" content="{{ config.author }}">
